services:
  database:
    container_name: postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    environment:
      POSTGRES_PASSWORD: '0901'
      POSTGRES_USER: postgres
      POSTGRES_DB: immich_db
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - /srv/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.512"
          memory: "1G"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname='immich_db' --username='postgres'"]
      interval: 1m
      timeout: 30s
      retries: 3
    restart: always
    networks:
      - homelab

networks:
  homelab:
    external: true
