services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    volumes:
      - /srv/immich/upload:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      DB_HOST: database
      DB_PORT: 5432
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "2283:3001"
    restart: always
    healthcheck:
      disable: false
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: "0.512"
          memory: "1G"

networks:
  default:
    name: homelab
    external: true
